#!/bin/zsh

### Colorize commands
alias ls='ls --color=auto'
alias grep='grep -i --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'
alias rgrep='rgrep --color=auto'
alias rg='rg -uu'
alias diff='diff --color=auto'
alias ip='ip --color=auto'

### Various
alias rm='rm -Iv'
alias cp='cp -ivr'
alias mv='mv -iv'
alias mkdir='mkdir -pv'
alias du='du -sh'
alias vi='lvim'
alias vim='nvim'

# alias nvim='nvim -u ~/.config/nvim/init.lua'
alias top='bpytop'
alias apt-get='apt-get --show-progress'

### LS & TREE
alias ll='ls -lAG'
alias la='ls -A'

# alias l='ls -F'
command -v lsd > /dev/null && alias ls='lsd --group-dirs first' && \
	alias tree='lsd --tree'
command -v colorls > /dev/null && alias ls='colorls --sd --gs' && \
	alias tree='colorls --tree'

### CAT & LESS
# command -v bat > /dev/null && \
	# alias bat='bat --theme=ansi' && \
	# alias cat='bat --pager=never' && \
	# alias less='bat'
# in debian the command is batcat
command -v batcat > /dev/null && \
	alias batcat='batcat --theme=ansi-dark' && \
	alias cat='batcat --pager=never' && \
	alias less='batcat'

### Misc
alias luamake=/home/cspencer/Installed/lua-language-server/3rd/luamake/luamake
alias wget="wget --hsts-file=$XDG_CACHE_HOME/wget-hsts"
alias gedit="devour gedit"
alias yarn='yarn --use-yarnrc "$XDG_CONFIG_HOME/yarn/config"'
alias pycharm="pycharm.sh"

# --------------------------- Important Commands -------------------------------
alias hp="pactl load-module module-alsa-sink device=hw:1,1"

alias kb_off="xinput disable 'AT Translated Set 2 keyboard' && notify-send 'Keyboard' 'Built-in keyboard disabled'"
alias kb_on="xinput enable 'AT Translated Set 2 keyboard' && notify-send 'Keyboard' 'Built-in keyboard enabled'"

alias get_thold="system76-power charge-thresholds"
alias ls_thold="system76-power charge-thresholds --list-profiles"
alias set_thold="system76-power charge-thresholds --profile"

alias ethernet_off="sudo ifconfig enp35s0 down"
alias ethernet_on="sudo ifconfig enp35s0 up"

alias polyconfig="vi $XDG_CONFIG_HOME/polybar/config"

alias backup='/usr/bin/git --git-dir=$HOME/.backup/ --work-tree=$HOME'

