#!/bin/sh

### Fix obvious typos
alias cd..="cd .."
alias pdw="pwd"

### Git
alias gts="git status"
alias gta="git add"
alias gtc="git commit"
alias gtp="git push"
alias glo="git log --oneline"
alias lg="lazygit"
alias cdg='cd $(git rev-parse --show-toplevel)'

### Backup Git
alias bks="backup status"
alias bka="backup add"
alias bkau="backup add -u && backup status"
alias bkc="backup commit -m"
alias bkp="backup push"

### Navigation Shortcuts
# alias lvp='cd ~/.local/share/lunarvim/lvim/lua/user/'
alias cdth="cd ~/.local/share/nvim/lazy/base46/lua/base46/themes"
alias cddwm="cd ~/.local/share/dwm"
alias cdsl="cd ~/.local/share/slstatus"
alias cdsb="cd ~/.local/statusbar"
alias nvz="\$EDITOR ~/.config/zsh/.zshrc"
alias lvz="\$EDITOR ~/.config/zsh/.zshrc"
alias qtc="\$EDITOR ~/.config/qtile/config.py"

### Programming Shortcuts
alias live="live-server ."
alias se="sudoedit"

### Colorize commands
command -v colorls >/dev/null && alias ls='colorls --sd --gs' &&
	alias tree='colorls --tree'
alias ls='ls -F --color=auto'
alias grep='grep -i --color=auto'
alias fgrep='grep -F --color=auto'
alias egrep='grep -E --color=auto'
alias rgrep='rgrep --color=auto'
alias rg='rg -uu'
alias diff='diff --color=auto'
alias ip='ip --color=auto'

### LS & TREE
alias ll='ls -lAG'
alias la='ls -A'

command -v lsd >/dev/null && alias ls='lsd --group-dirs first' &&
	alias tree='lsd --tree'

## CAT & LESS
command -v bat >/dev/null &&
	alias bat='bat --theme=ansi' &&
	alias cat='bat --pager=never' &&
	alias less='bat'
# # in debian the command is batcat
# command -v batcat > /dev/null && \
# 	alias batcat='batcat --theme=ansi-dark' && \
# 	alias cat='batcat --pager=never' && \
# 	alias less='batcat'

### Various
alias sz='source ~/.config/zsh/.zshrc'
alias rm='rm -Iv'
alias cp='cp -ivr'
alias mv='mv -iv'
alias mkdir='mkdir -pv'
alias du='du -sh'
alias df='df -Th'
alias free='free -mt'

if [ -x "$(command -v lvim)" ]; then
	alias lv='lvim'
	alias lvims='lvim -S'
	alias vi="nvim"
	alias nv='lvim'
	alias nvims="nvim -S"
elif [ -x "$(command -v nvim)" ]; then
	alias vi="nvim"
	alias nv='nvim'
	alias nvims="nvim -S"
fi

if [ -x "$(command -v "$HOME"/neovim/bin/nvim)" ]; then
    alias nvd="~/neovim/bin/nvim"
    alias nvds="~/neovim/bin/nvim -S"
    alias nv="~/neovim/bin/nvim"
    alias nvs="~/neovim/bin/nvim -S"
fi

alias top='btop'

### DNF
alias dnf="sudo dnf"
alias dnfi="dnf install"
alias dnfy="dnf -y install"
alias dnfc="dnf check-update"

### Pacman
alias update="sudo pacman -Syyu && pacmod || pacmod"
alias upall="paru -Syu --noconfirm && pacmod || pacmod"
alias pacman='sudo pacman --color auto'
alias upgraded="grep -iE 'installed|upgraded' /var/log/pacman.log"
alias ram='rate-mirrors --allow-root --disable-comments --protocol https arch | sudo tee /etc/pacman.d/mirrorlist && pacmod'
alias paruskip='paru -S --mflags --skipinteg'
alias yayskip='yay -S --mflags --skipinteg'

#Cleanup orphaned packages
alias cleanup='sudo pacman -Rns $(pacman -Qtdq)'

#mounting the folder Public for exchange between host and guest on virtualbox
alias vbm="sudo /usr/local/bin/arcolinux-vbox-share"

#enabling vmware services
alias start-vmware="sudo systemctl enable --now vmtoolsd.service"
alias sv="sudo systemctl enable --now vmtoolsd.service"

#youtube download
alias yta-aac="yt-dlp --extract-audio --audio-format aac "
alias yta-best="yt-dlp --extract-audio --audio-format best "
alias yta-flac="yt-dlp --extract-audio --audio-format flac "
alias yta-mp3="yt-dlp --extract-audio --audio-format mp3 "
alias ytv-best="yt-dlp -f 'bestvideo[ext=mp4]+bestaudio[ext=m4a]/bestvideo+bestaudio' --merge-output-format mp4 "

#Recent Installed Packages
alias rip="expac --timefmt='%Y-%m-%d %T' '%l\t%n %v' | sort | tail -200 | nl"
alias riplong="expac --timefmt='%Y-%m-%d %T' '%l\t%n %v' | sort | tail -3000 | nl"

#iso and version used to install ArcoLinux
iso() {
	awk -F '=' '/ISO/ {print $2}' /etc/dev-rel
}

#clear
# alias clean="clear; seq 1 $(tput cols) | sort -R | sparklines | lolcat"

#search content with ripgrep
alias rg="rg --sort path"

#get the error messages from journalctl
alias jctl="journalctl -p 3 -xb"

#nano for important configuration files
#know what you do in these files
alias nlxdm="sudo \$EDITOR /etc/lxdm/lxdm.conf"
alias nlightdm="sudo \$EDITOR /etc/lightdm/lightdm.conf"
alias npacman="sudo \$EDITOR /etc/pacman.conf"
alias ngrub="sudo \$EDITOR /etc/default/grub"
alias nconfgrub="sudo \$EDITOR /boot/grub/grub.cfg"
alias nmkinitcpio="sudo \$EDITOR /etc/mkinitcpio.conf"
alias nmirrorlist="sudo \$EDITOR /etc/pacman.d/mirrorlist"
alias narcomirrorlist='sudo nano /etc/pacman.d/arcolinux-mirrorlist'
alias nsddm="sudo \$EDITOR /etc/sddm.conf"
alias nsddmk="sudo \$EDITOR /etc/sddm.conf.d/kde_settings.conf"
alias nfstab="sudo \$EDITOR /etc/fstab"
alias nnsswitch="sudo \$EDITOR /etc/nsswitch.conf"
alias nsamba="sudo \$EDITOR /etc/samba/smb.conf"
alias ngnupgconf="sudo nano /etc/pacman.d/gnupg/gpg.conf"
alias nhosts="sudo \$EDITOR /etc/hosts"
alias nb="\$EDITOR ~/.bashrc"
alias nz="\$EDITOR ~/.zshrc"
alias nf="EDITOR ~/.config/fish/config.fish"

#gpg
#verify signature for isos
alias gpg-check="gpg2 --keyserver-options auto-key-retrieve --verify"
alias fix-gpg-check="gpg2 --keyserver-options auto-key-retrieve --verify"
#receive the key of a developer
alias gpg-retrieve="gpg2 --keyserver-options auto-key-retrieve --receive-keys"
alias fix-gpg-retrieve="gpg2 --keyserver-options auto-key-retrieve --receive-keys"
alias fix-keyserver="[ -d ~/.gnupg ] || mkdir ~/.gnupg ; cp /etc/pacman.d/gnupg/gpg.conf ~/.gnupg/ ; echo 'done'"

#fixes
alias fix-permissions="sudo chown -R \$USER:\$USER ~/.config ~/.local"
alias keyfix="/usr/local/bin/arcolinux-fix-pacman-databases-and-keys"
alias key-fix="/usr/local/bin/arcolinux-fix-pacman-databases-and-keys"
alias keys-fix="/usr/local/bin/arcolinux-fix-pacman-databases-and-keys"
alias fixkey="/usr/local/bin/arcolinux-fix-pacman-databases-and-keys"
alias fixkeys="/usr/local/bin/arcolinux-fix-pacman-databases-and-keys"
alias fix-key="/usr/local/bin/arcolinux-fix-pacman-databases-and-keys"
alias fix-keys="/usr/local/bin/arcolinux-fix-pacman-databases-and-keys"
alias fix-sddm-config="/usr/local/bin/arcolinux-fix-sddm-config"
alias fix-pacman-conf="/usr/local/bin/arcolinux-fix-pacman-conf"
alias fix-pacman-keyserver="/usr/local/bin/arcolinux-fix-pacman-gpg-conf"

#maintenance
alias big="expac -H M '%m\t%n' | sort -h | nl"
alias downgrada="sudo downgrade --ala-url https://ant.seedhost.eu/arcolinux/"

#hblock (stop tracking with hblock)
#use unhblock to stop using hblock
alias unhblock="hblock -S none -D none"

#systeminfo
alias probe="sudo -E hw-probe -all -upload"
alias sysfailed="systemctl list-units --failed"

#shutdown or reboot
alias ssn="sudo shutdown now"
alias sr="sudo reboot"

#update betterlockscreen images
# alias bls="betterlockscreen -u /usr/share/backgrounds/arcolinux/"

#give the list of all installed desktops - xsessions desktops
alias xd="ls /usr/share/xsessions"

### Misc
alias luamake=/home/cspencer/Installed/lua-language-server/3rd/luamake/luamake
alias wget="wget -c --hsts-file=\$XDG_CACHE_HOME/wget-hsts"
alias gedit="devour gedit"
alias yarn='yarn --use-yarnrc "$XDG_CONFIG_HOME/yarn/config"'
alias update-grub="grub-mkconfig -o /boot/grub/grub.cfg"
alias install-grub-efi="sudo grub-install --target=x86_64-efi --efi-directory=/boot/efi"
alias hsc="headsetcontrol"
alias codium="flatpak run com.vscodium.codium"

# --------------------------- Important Commands -------------------------------
alias hp="pactl load-module module-alsa-sink device=hw:1,1"

alias kb_off="xinput disable 'AT Translated Set 2 keyboard' && notify-send 'Keyboard' 'Built-in keyboard disabled'"
alias kb_on="xinput enable 'AT Translated Set 2 keyboard' && notify-send 'Keyboard' 'Built-in keyboard enabled'"

alias get_thold="system76-power charge-thresholds"
alias ls_thold="system76-power charge-thresholds --list-profiles"
alias set_thold="system76-power charge-thresholds --profile"

alias ethernet_off="sudo ifconfig enp35s0 down"
alias ethernet_on="sudo ifconfig enp35s0 up"

alias polyconfig="vi \$XDG_CONFIG_HOME/polybar/config"

alias backup='/usr/bin/git --git-dir=$HOME/.backup/ --work-tree=$HOME'

alias notify-send="sudo -u cs DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus notify-send"
