#!/usr/bin/env bash

ps aux | grep /usr/bin/bpytop && { killall bpytop && exit; } || { setsid -f "$TERMINAL" -e bpytop -b "cpu proc"\
  && qtile cmd-obj -o window -f set_size_floating -a 1280 810 \
  & qtile cmd-obj -o window -f set_position_floating -a 333 28; }
