#!/usr/bin/env bash

# Shows the current moon phase.

moonfile="$XDG_CACHE_HOME/moonphase"

# [ "$(stat -c %y "$moonfile" 2>/dev/null | cut -d' ' -f1)" = "$(date '+%Y-%m-%d')" ] ||
x=0
until [ "$x" -ge 3 ]; do
  curl -sf "wttr.in/?format=%m" > "$moonfile" && break
  x=$((x+1))
  sleep 1
done

icon="$(cat "$moonfile")"

case "$icon" in
	 ) name="New" ;;
	 ) name="Waxing Crescent" ;;
	 ) name="First Quarter" ;;
	 ) name="Waxing Gibbous" ;;
	 ) name="Full" ;;
	 ) name="Waning Gibbous" ;;
	 ) name="Last Quarter" ;;
	 ) name="Waning Crescent" ;;
	*) exit 1 ;;
esac

# case "$icon" in
# 	🌑) name="New" ;;
# 	🌒) name="Waxing Crescent" ;;
# 	🌓) name="First Quarter" ;;
# 	🌔) name="Waxing Gibbous" ;;
# 	🌕) name="Full" ;;
# 	🌖) name="Waning Gibbous" ;;
# 	🌗) name="Last Quarter" ;;
# 	🌘) name="Waning Crescent" ;;
# 	*) exit 1 ;;
# esac

