#!/usr/bin/env bash

options=$\
(
  echo \
  "Power Profile 
Charge Threshold" | 
  rofi -dmenu -p "System 76 Power" # -location 3 -yoffset 28 -l 2
)


[[ -z $options ]] && exit
[[ $options = Power* ]] && s76-power-pp
[[ $options = *Threshold ]] && s76-power-ct

