#!/usr/bin/env bash

options=$\
(
  echo \
  "Full Charge
Balanced
Max Lifespan" | 
  rofi -dmenu -p "Charge Threshold" -location 3 -yoffset 28 -l 3
)


[[ -z $options ]] && notify-send "$(system76-power charge-thresholds)" && exit
[[ $options = Full* ]] && system76-power charge-thresholds --profile full_charge
[[ $options = *Bal* ]] && system76-power charge-thresholds --profile balanced
[[ $options = *Max* ]] && system76-power charge-thresholds --profile max_lifespan

notify-send "$(system76-power charge-thresholds)"
