#!/usr/bin/env bash

options=$\
(
  echo \
  "Battery
Balanced
Performance" | 
  rofi -dmenu -p "Power Profile"
)


[[ -z $options ]] && notify-send "$(system76-power profile)" && exit

[[ $options = Bat* ]] && system76-power profile battery && \
  echo Low > ~/.cache/power-profile && \
  qtile cmd-obj -o widget indicator -f update -a Low

[[ $options = *Bal* ]] && system76-power profile balanced && \
  echo Bal > ~/.cache/power-profile && \
  qtile cmd-obj -o widget indicator -f update -a Bal

[[ $options = *Per* ]] && system76-power profile performance && \
  echo Max > ~/.cache/power-profile && \
  qtile cmd-obj -o widget indicator -f update -a Max

notify-send "$(system76-power profile)"
