#!/usr/bin/env bash

options=$\
(
  echo \
  "Power Profile 
Charge Threshold" | 
  rofi -dmenu -p "System 76 Power"
)


[[ -z $options ]] && exit
[[ $options = Power* ]] && s76-power-pp
[[ $options = *Threshold ]] && s76-power-ct

