print('Good Morning Hunnie Pie.')
print('Would you like a coffee?')
print('')
input('your answer: ')
print('')
print('Coffee coming right up my love :)')
print('Would you like anything else?')
print('')
input()
print('')
print('I make a special for you!')
print('Am I your hunnie guy?')
print('')
input()
print('')
print('I am so happy you are my wifey lady.')
print('I love you :*')
