/* Bar functionality */
#include "bar_indicators.c"
#include "bar_tagicons.c"
#include "bar.c"

#include "bar_ltsymbol.c"
#include "bar_status.c"
#include "bar_status2d.c"
#include "bar_statusbutton.c"
#include "bar_winicon.c"
#include "bar_tags.c"
#include "bar_tagpreview.c"
#include "bar_wintitle.c"
#include "bar_systray.c"
#include "bar_layoutmenu.c"

/* Other patches */
#include "autostart.c"
#include "cfacts.c"
#include "cyclelayouts.c"
#include "dragcfact.c"
#include "movestack.c"
#include "pertag.c"
#include "rotatestack.c"
#include "scratchpad.c"
#include "shiftview.c"
#include "tagswapmon.c"
#include "togglefullscreen.c"
#include "vanitygaps.c"
#include "warp.c"
#include "dragmfact.c"
/* Layouts */
#include "layout_facts.c"
#include "layout_bstack.c"
#include "layout_centeredmaster.c"
#include "layout_centeredfloatingmaster.c"
#include "layout_deck.c"
#include "layout_grid.c"
#include "layout_monocle.c"
#include "layout_tile.c"

