/* Bar functionality */
#include "bar_indicators.h"
#include "bar_tagicons.h"
#include "bar.h"

#include "bar_ltsymbol.h"
#include "bar_status.h"
#include "bar_status2d.h"
#include "bar_statusbutton.h"
#include "bar_winicon.h"
#include "bar_tags.h"
#include "bar_tagpreview.h"
#include "bar_wintitle.h"
#include "bar_systray.h"
#include "bar_layoutmenu.h"

/* Other patches */
#include "autostart.h"
#include "cfacts.h"
#include "cyclelayouts.h"
#include "dragcfact.h"
#include "dragmfact.h"
#include "movestack.h"
#include "pertag.h"
#include "rotatestack.h"
#include "scratchpad.h"
#include "shiftview.h"
#include "tagswapmon.h"
#include "togglefullscreen.h"
#include "vanitygaps.h"
#include "warp.h"
/* Layouts */
#include "layout_bstack.h"
#include "layout_centeredmaster.h"
#include "layout_centeredfloatingmaster.h"
#include "layout_deck.h"
#include "layout_grid.h"
#include "layout_monocle.h"
#include "layout_tile.h"

